### ISSUE TITLE
Adding your gem "destroys" rails_admin's views

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [openjaf/rails_admin_dynamic_charts#3]
I have added all yor suggested gems to my project.

When I open `localhost:3000/admin` it shows me an error:

`Sprockets::Rails::Helper::AssetFilteredError in RailsAdmin::Main#index`

It asks to add `highcharts.js` to `assets.rb` file.

When I open my admin page, now it looks like this:

![image](https://cloud.githubusercontent.com/assets/8684688/9131808/b5469d32-3d10-11e5-8da0-e2a235c5bdee.png)

Is your gem is unstable or I'm missing something?

**Comment by fmh** [comment]
+1, same issue

**Comment by SuperMasterBlasterLaser** [comment]
I think this gem is unstable and does not get updates.

**Comment by fmh** [comment]
Not say that. We should contribute to its maintenance +++

**Comment by pecuerre** [comment]
hi everyone:
sorry for the current state of the gem, the original author of that is on vacations for a few more weeks. in the first days of september we will continue to work again. sorry for the inconvenience.

**Comment by fmh** [comment]
any news ?

**Comment by jessesanford** [comment]
I would also like to use this gem. Is it abandoned?

**Comment by jessesanford** [comment]
I created PR #5 which solves most of the visual issues you see.
